sudo: required
services:
 - docker
env:
  global:
    - REGISTRY_USER=nachwera
    - REGISTRY_PASS=knightf6

script:
 - docker build --tag wanyama/myimage .
 - docker run wanyama/myimage

after_script:
 - docker images

before_deploy:
 - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
 provider: script
 script: docker push wanyama/myimage
 on:
  branch: master
 
