sudo: required
services:
 - docker
env:
  global:
    - REGISTRY_USER=nachwera
    - REGISTRY_PASS=knightf6

script:
 - docker build --tag wanyama/facial-recognition .
 - docker run wanyama/facial-recognition

after_script:
 - docker images

before_deploy:
 - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
 provider: script
 script: docker push wanyama/facial-recognition
 on:
  branch: master
 
